#!/bin/sh
_brewsetup() {
  brew install \
    firefox ghostty zed ukelele keepassxc pinta \
    visual-studio-code font-cascadia-code-nf \
    tmux wget mc htop ncdu micro fzf ripgrep jq \
    yazi carapace zoxide git-delta gitui tree bat \
    deno aria2 entr xz pixz pigz sevenzip podman pstree
}
_brewsetup; unset _brewsetup
