#!/bin/sh
_remotedevmachinesetup() {
  local distribid=`grep DISTRIB_ID /etc/*-release | awk -F '=' '{print tolower($2)}'`
  if [ "$distribid" = 'ubuntu' ]; then
    sudo apt install -y curl git zsh tmux mc htop fzf ripgrep nano
  fi

  curl https://artas90.github.io/dotfiles | sh
  curl https://artas90.github.io/fzf | sudo sh
  curl https://artas90.github.io/micro | sudo sh
  curl https://artas90.github.io/yazi | sudo sh
  # curl https://artas90.github.io/fd | sudo sh
  # curl https://artas90.github.io/sd | sudo sh

  echo >> "$HOME/.bash_profile"
  echo "export TERM=xterm-256color" >> "$HOME/.bash_profile"

  echo >> $HOME/.tmux.conf
  echo "set-option -g default-shell \""`which zsh`"\"" >> $HOME/.tmux.conf
}
_remotedevmachinesetup; unset _remotedevmachinesetup
