#!/bin/sh
_fdfindfetch() {
  if [ ! `whoami` = "root" ]; then
    echo "error: must be run as root"; return
  fi

  local rel="https://api.github.com/repos/sharkdp/fd/releases/latest"
  local ver=`curl -s "${rel}" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | tr -d 'v'`
  local pkgname="fd-v${ver}-$(uname -m)-unknown-linux-musl"
  local pkgurl="https://github.com/sharkdp/fd/releases/download/v${ver}/${pkgname}.tar.gz"

  curl -sL  "${pkgurl}" | tar xz -C . && \
  mv -f ./${pkgname}/fd /usr/bin/fd && \
  chmod 755 /usr/bin/fd && \
  rm -rf ${pkgname} && \
  echo "created /usr/bin/fd (v${ver})"
}
_fdfindfetch; unset _fdfindfetch
