#!/bin/sh
_getfzf() {
  local from="$1/$3"
  local to="$2/$3"
  curl -s "$from" > "$to" && echo "$to -> $to"
}
_getfzfall() {
  local ghfz="https://raw.githubusercontent.com/junegunn/fzf/master/shell"
  local destfz=""

  if [ `whoami` = "root" ]; then
    destfz="/usr/local/opt/fzf/shell"
  else
    destfz="$HOME/.local/share/fzf/shell"
  fi

  mkdir -p $destfz

  _getfzf "$ghfz" "$destfz" "completion.zsh"
  _getfzf "$ghfz" "$destfz" "key-bindings.zsh"
}
unset _getfzf _getfzfall
