#!/bin/sh
_legofetch() {
  if [ ! `whoami` = "root" ]; then
    echo "error: must be run as root"; return
  fi

  local arch=""
  case "$(uname -m)" in
    x86_64)  arch="amd64" ;;
    aarch64) arch="arm64" ;;
    *)       echo "error: unknown architecture"; return ;;
  esac

  local rel="https://api.github.com/repos/go-acme/lego/releases/latest"
  local ver=`curl -s "${rel}" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | tr -d 'v'`
  local pkg="https://github.com/go-acme/lego/releases/download/v${ver}/lego_v${ver}_linux_${arch}.tar.gz"

  mkdir _legopkg && \
  curl -sL  "${pkg}" | tar xz -C ./_legopkg && \
  mv -f ./_legopkg/lego /usr/bin/lego && \
  chmod 755 /usr/bin/lego && \
  rm -rf _legopkg && \
  echo "created /usr/bin/lego (v${ver})"
}
_legofetch; unset _legofetch
