#!/bin/sh
_sdsedfetch() {
  if [ ! `whoami` = "root" ]; then
    echo "error: must be run as root"; return
  fi

  local rel="https://api.github.com/repos/chmln/sd/releases/latest"
  local ver=`curl -s "${rel}" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | tr -d 'v'`
  local pkgname="sd-v${ver}-$(uname -m)-unknown-linux-musl"
  local pkgurl="https://github.com/chmln/sd/releases/download/v${ver}/${pkgname}.tar.gz"

  curl -sL  "${pkgurl}" | tar xz -C . && \
  mv -f ./${pkgname}/sd /usr/bin/sd && \
  chmod 755 /usr/bin/sd && \
  rm -rf ${pkgname} && \
  echo "created /usr/bin/sd (v${ver})"
}
_sdsedfetch; unset _sdsedfetch
