#!/bin/sh
_netbirdfetch() {
  if [ ! `whoami` = "root" ]; then
    echo "error: must be run as root"; return
  fi

  case "$(uname -m)" in
    x86_64)  arch="amd64" ;;
    aarch64) arch="arm64" ;;
    *)       echo "error: unknown architecture"; return ;;
  esac

  local url="https://api.github.com/repos/netbirdio/netbird/releases/latest"
  local ver=`curl -s "${url}" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | tr -d 'v'`
  local pkg="https://github.com/netbirdio/netbird/releases/download/v${ver}/netbird_${ver}_linux_${arch}.tar.gz"

  mkdir ./netbirdtmp && \
  curl -sL "${pkg}" | tar xz -C ./netbirdtmp && \
  mv -f ./netbirdtmp/netbird /usr/bin/netbird && \
  chown root:root /usr/bin/netbird && \
  chmod 755 /usr/bin/netbird && \
  rm -rf ./netbirdtmp && \
  echo "created /usr/bin/netbird (v${ver})"

  netbird service stop      2>/dev/null
  netbird service uninstall 2>/dev/null
  netbird service install
  netbird service start

  # For Synology
  # curl -sL https://skyfalconua.github.io/netbird/tun-enable | sudo tee /usr/bin/netbird-tun-enable > /dev/null
  # sudo chmod 755 /usr/bin/netbird-tun-enable
}
_netbirdfetch; unset _netbirdfetch
